import { Agreement, SignetExport } from './types';
import { founderStorage } from './storage';

// Generate Signet export format
export function generateSignetExport(agreement: Agreement): SignetExport | null {
  const founderA = founderStorage.findById(agreement.founderAId);
  const founderB = founderStorage.findById(agreement.founderBId);
  
  if (!founderA || !founderB) {
    return null;
  }
  
  const currentVersion = agreement.versions[agreement.currentVersion];
  if (!currentVersion) {
    return null;
  }
  
  const signetExport: SignetExport = {
    agreementId: agreement.id,
    exportedAt: new Date().toISOString(),
    parties: {
      companyA: {
        name: founderA.companyName,
        founder: founderA.founderName,
        equityOffered: currentVersion.equityFromCompanyA,
      },
      companyB: {
        name: founderB.companyName,
        founder: founderB.founderName,
        equityOffered: currentVersion.equityFromCompanyB,
      },
    },
    terms: {
      equitySwapPercentages: {
        companyAToB: currentVersion.equityFromCompanyA,
        companyBToA: currentVersion.equityFromCompanyB,
      },
      agreementNotes: currentVersion.notes,
    },
    signatures: {
      founderA: {
        name: founderA.founderName,
        signedAt: new Date().toISOString(),
      },
      founderB: {
        name: founderB.founderName,
        signedAt: new Date().toISOString(),
      },
    },
    legalText: generateLegalText(founderA.companyName, founderB.companyName, currentVersion.equityFromCompanyA, currentVersion.equityFromCompanyB, currentVersion.notes),
  };
  
  return signetExport;
}

// Generate legal contract text
function generateLegalText(
  companyA: string,
  companyB: string,
  equityFromA: number,
  equityFromB: number,
  notes: string
): string {
  return `
EQUITY SWAP AGREEMENT

This Equity Swap Agreement ("Agreement") is entered into between ${companyA} ("Company A") and ${companyB} ("Company B").

TERMS:
1. Company A agrees to transfer ${equityFromA}% of its equity to Company B.
2. Company B agrees to transfer ${equityFromB}% of its equity to Company A.
3. This swap is executed simultaneously upon signing of this agreement.

ADDITIONAL TERMS:
${notes || 'No additional terms specified.'}

REPRESENTATIONS AND WARRANTIES:
Each party represents and warrants that:
- They have full corporate power and authority to enter into this Agreement
- The execution and performance of this Agreement has been duly authorized
- This Agreement constitutes a legal, valid, and binding obligation

GOVERNING LAW:
This Agreement shall be governed by and construed in accordance with applicable corporate law.

ENTIRE AGREEMENT:
This Agreement constitutes the entire agreement between the parties and supersedes all prior negotiations, representations, or agreements relating to the subject matter hereof.

Generated by Polycentric on ${new Date().toLocaleDateString()}
  `.trim();
}

// Download JSON file
export function downloadSignetExport(signetExport: SignetExport): void {
  const jsonString = JSON.stringify(signetExport, null, 2);
  const blob = new Blob([jsonString], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = `polycentric-agreement-${signetExport.agreementId}-${new Date().toISOString().split('T')[0]}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  URL.revokeObjectURL(url);
}

// Export agreement
export function exportAgreement(agreement: Agreement): { success: boolean; error?: string } {
  if (agreement.status !== 'approved' && agreement.status !== 'completed') {
    return { success: false, error: 'Can only export approved or completed agreements' };
  }
  
  const signetExport = generateSignetExport(agreement);
  if (!signetExport) {
    return { success: false, error: 'Failed to generate export data' };
  }
  
  try {
    downloadSignetExport(signetExport);
    return { success: true };
  } catch (error) {
    return { success: false, error: 'Failed to download export file' };
  }
}
